NUM_ORDERS = 1000
ORDER_CANCEL_PROBABILITY = 0.2
RANDOM_SEED = 42
FIX_CONFIG_FILE_PATH = "fix.cfg"
FIX_CLIENT_WAIT_TIME = 120
SYMBOLS = ["MSFT", "AAPL", "BAC"]
REFERENCE_PRICES = {
            "MSFT": 430.19,
            "AAPL": 222.23,
            "BAC": 38.58
}